### ISSUE TITLE
An established connection was aborted by the software in your host machine

### ISSUE THREAD

**Issue by nikolas310** [cdrx/django-admin-menu#7]
Dont know where is the error. Using django 2.0.2

[25/Mar/2018 01:09:16] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 8192
Traceback (most recent call last):
  File "c:\program files\python36\Lib\wsgiref\handlers.py", line 138, in run
    self.finish_response()
  File "c:\program files\python36\Lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
  File "c:\program files\python36\Lib\wsgiref\handlers.py", line 274, in write
    self.send_headers()
  File "c:\program files\python36\Lib\wsgiref\handlers.py", line 332, in send_headers
    self.send_preamble()
  File "c:\program files\python36\Lib\wsgiref\handlers.py", line 255, in send_preamble
    ('Date: %s\r\n' % format_date_time(time.time())).encode('iso-8859-1')
  File "c:\program files\python36\Lib\wsgiref\handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "c:\program files\python36\Lib\socketserver.py", line 775, in write
    self._sock.sendall(b)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
[25/Mar/2018 01:09:16] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 55977)
Traceback (most recent call last):
  File "c:\program files\python36\Lib\wsgiref\handlers.py", line 138, in run
    self.finish_response()
  File "c:\program files\python36\Lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
  File "c:\program files\python36\Lib\wsgiref\handlers.py", line 274, in write
    self.send_headers()
  File "c:\program files\python36\Lib\wsgiref\handlers.py", line 332, in send_headers
    self.send_preamble()
  File "c:\program files\python36\Lib\wsgiref\handlers.py", line 255, in send_preamble
    ('Date: %s\r\n' % format_date_time(time.time())).encode('iso-8859-1')
  File "c:\program files\python36\Lib\wsgiref\handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "c:\program files\python36\Lib\socketserver.py", line 775, in write
    self._sock.sendall(b)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python36\Lib\wsgiref\handlers.py", line 141, in run
    self.handle_error()
  File "D:\Own\venv\lib\site-packages\django\core\servers\basehttp.py", line 86, in handle_error
    super().handle_error()
  File "c:\program files\python36\Lib\wsgiref\handlers.py", line 368, in handle_error
    self.finish_response()
  File "c:\program files\python36\Lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
  File "c:\program files\python36\Lib\wsgiref\handlers.py", line 274, in write
    self.send_headers()
  File "c:\program files\python36\Lib\wsgiref\handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "c:\program files\python36\Lib\wsgiref\handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python36\Lib\socketserver.py", line 639, in process_request_thread
    self.finish_request(request, client_address)
  File "c:\program files\python36\Lib\socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "c:\program files\python36\Lib\socketserver.py", line 696, in __init__
    self.handle()
  File "D:\Own\venv\lib\site-packages\django\core\servers\basehttp.py", line 154, in handle
    handler.run(self.server.get_app())
  File "c:\program files\python36\Lib\wsgiref\handlers.py", line 144, in run
    self.close()
  File "c:\program files\python36\Lib\wsgiref\simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
----------------------------------------
[25/Mar/2018 01:09:16] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 8192
Traceback (most recent call last):
  File "c:\program files\python36\Lib\wsgiref\handlers.py", line 138, in run
    self.finish_response()
  File "c:\program files\python36\Lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
  File "c:\program files\python36\Lib\wsgiref\handlers.py", line 274, in write
    self.send_headers()
  File "c:\program files\python36\Lib\wsgiref\handlers.py", line 332, in send_headers
    self.send_preamble()
  File "c:\program files\python36\Lib\wsgiref\handlers.py", line 255, in send_preamble
    ('Date: %s\r\n' % format_date_time(time.time())).encode('iso-8859-1')
  File "c:\program files\python36\Lib\wsgiref\handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "c:\program files\python36\Lib\socketserver.py", line 775, in write
    self._sock.sendall(b)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
[25/Mar/2018 01:09:16] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 55978)
Traceback (most recent call last):
  File "c:\program files\python36\Lib\wsgiref\handlers.py", line 138, in run
    self.finish_response()
  File "c:\program files\python36\Lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
  File "c:\program files\python36\Lib\wsgiref\handlers.py", line 274, in write
    self.send_headers()
  File "c:\program files\python36\Lib\wsgiref\handlers.py", line 332, in send_headers
    self.send_preamble()
  File "c:\program files\python36\Lib\wsgiref\handlers.py", line 255, in send_preamble
    ('Date: %s\r\n' % format_date_time(time.time())).encode('iso-8859-1')
  File "c:\program files\python36\Lib\wsgiref\handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "c:\program files\python36\Lib\socketserver.py", line 775, in write
    self._sock.sendall(b)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python36\Lib\wsgiref\handlers.py", line 141, in run
    self.handle_error()
  File "D:\Own\venv\lib\site-packages\django\core\servers\basehttp.py", line 86, in handle_error
    super().handle_error()
  File "c:\program files\python36\Lib\wsgiref\handlers.py", line 368, in handle_error
    self.finish_response()
  File "c:\program files\python36\Lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
  File "c:\program files\python36\Lib\wsgiref\handlers.py", line 274, in write
    self.send_headers()
  File "c:\program files\python36\Lib\wsgiref\handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "c:\program files\python36\Lib\wsgiref\handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python36\Lib\socketserver.py", line 639, in process_request_thread
    self.finish_request(request, client_address)
  File "c:\program files\python36\Lib\socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "c:\program files\python36\Lib\socketserver.py", line 696, in __init__
    self.handle()
  File "D:\Own\venv\lib\site-packages\django\core\servers\basehttp.py", line 154, in handle
    handler.run(self.server.get_app())
  File "c:\program files\python36\Lib\wsgiref\handlers.py", line 144, in run
    self.close()
  File "c:\program files\python36\Lib\wsgiref\simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
----------------------------------------

**Comment by cdrx** [comment]
It doesn't look like this is an issue with `django-admin-menu` but something else in your Django setup
